apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-dev-01
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps/dev-01
  prune: true
  sourceRef:
    kind: GitRepository
    name: rendered-dev
  targetNamespace: dev-01

