# apps-dev-01.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: dev-01
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-dev-01
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps/dev-01
  prune: true
  sourceRef:
    kind: GitRepository
    name: rendered-dev
  targetNamespace: dev-01
  # Global variables for dev cluster
  postBuild:
    substitute:
      apps_env: "dev-01"
      apps_domain: "dev-01.mycluster.com"

