apiVersion: v1
kind: Namespace
metadata:
  name: apps-stage-01
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-stage-01
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps/stage-01
  prune: true
  sourceRef:
    kind: GitRepository
    name: rendered-stage
  targetNamespace: apps-stage-01

