apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
spec:
  kustomize:
    patches:
      - patch: |
          apiVersion: source.toolkit.fluxcd.io/v1
          kind: GitRepository
          metadata:
            name: rendered-dev
            namespace: flux-system
          spec:
            interval: 1m
            url: ssh://git@github.com/skiyl9x/portfolio
            ref:
              branch: dev      # <- dev branch ли rendered manifests
        target:
          kind: GitRepository
      - patch: |
          apiVersion: source.toolkit.fluxcd.io/v1
          kind: GitRepository
          metadata:
            name: rendered-stage
            namespace: flux-system
          spec:
            interval: 1m
            url: ssh://git@github.com/skiyl9x/portfolio
            ref:
              branch: stage      # <- stage branch ли rendered manifests
        target:
          kind: GitRepository
      - patch: |
          apiVersion: source.toolkit.fluxcd.io/v1beta2
          kind: HelmRepository
          metadata:
            name: bitnami-oci
            namespace: flux-system
          spec:
            interval: 1h
            type: oci # <--- This is the key fix!
            url: oci://registry-1.docker.io/bitnamicharts
        target:
          kind: HelmRepository
      - patch: |
          apiVersion: source.toolkit.fluxcd.io/v1
          kind: HelmRepository
          metadata:
            name: bitnami
            namespace: flux-system
          spec:
            interval: 1h
            url: https://charts.bitnami.com/bitnami
        target:
          kind: HelmRepository
  distribution:
    version: "2.7.x"
    registry: "ghcr.io/fluxcd"
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
  cluster:
    type: kubernetes
    multitenant: false
    networkPolicy: true
    domain: "cluster.local"
  sync:
    kind: GitRepository
    url: "ssh://git@github.com/skiyl9x/portfolio"
    ref: "refs/heads/main"
    path: "clusters/dev"
    pullSecret: "flux-system"
