# Source - https://stackoverflow.com/q/64238522
# Posted by W.K.S, modified by community. See post 'Timeline' for change history
# Retrieved 2026-02-08, License - CC BY-SA 4.0

# Source - https://stackoverflow.com/a/64258970
# Posted by Matt
# Retrieved 2026-02-08, License - CC BY-SA 4.0

apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
spec:
  replicas: 3
  image: rabbitmq:3.12-management
  persistence:
    storageClassName: local-storage
    storage: 20Gi
  override:
    statefulSet:
      spec:
        template:
          spec:
            initContainers:
              - name: volume-permissions
                image: busybox
                command: ["sh", "-c", "chown -R 999:999 /var/lib/rabbitmq && chmod -R 775 /var/lib/rabbitmq"]
                securityContext:
                  runAsUser: 0      # Run as root to allow chown
                  runAsNonRoot: false
                volumeMounts:
                  - name: persistence
                    mountPath: /var/lib/rabbitmq
            securityContext:
              fsGroup: 999
              runAsUser: 999
            containers:
              - name: rabbitmq
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 20Gi
  hostPath:
    path: /mnt/app/rabbitmq
    type: DirectoryOrCreate

