apiVersion: v1
kind: Namespace
metadata:
  name: dev-01
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: dev-01
spec:
  ports:
  - port: 80
  selector:
    app: whoami
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: dev-01
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - image: traefik/whoami
        name: whoami
        ports:
        - containerPort: 80
