apiVersion: v1
kind: Service
metadata:
  name: whoami
spec:
  ports:
  - port: 80
  selector:
    app: whoami
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - image: traefik/whoami
        name: whoami
        ports:
        - containerPort: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: whoami
spec:
  hostnames:
  - whoami.${apps_domain}
  parentRefs:
  - name: traefik-gateway
    namespace: traefik-system
  rules:
  - backendRefs:
    - name: whoami
      port: 80
    matches:
    - path:
        type: PathPrefix
        value: /
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
spec:
  chart:
    spec:
      chart: web-app
      sourceRef:
        kind: HelmRepository
        name: skiyl9x-helm-charts
        namespace: flux-system
      version: 0.1.6
  interval: 1m
  values:
    appsDomain: ${apps_domain}
    env:
      AMQP_HOST: rabbitmq.rabbitmq-system.svc
      SERVICE_LOG_LEVEL: debug
    gateway:
      name: traefik-gateway
      namespace: traefik-system
    image:
      repository: nginx
      tag: "1.22"
    nameOverride: nginx
    replicaCount: 4
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: web-page
spec:
  chart:
    spec:
      chart: web-app
      sourceRef:
        kind: HelmRepository
        name: skiyl9x-helm-charts
        namespace: flux-system
      version: 0.1.7
  interval: 1m
  values:
    appsDomain: ${apps_domain}
    gateway:
      name: traefik-gateway
      namespace: traefik-system
    image:
      repository: ghcr.io/skiyl9x/web-page
      tag: main-e26a092
    nameOverride: web-page
    replicaCount: 3
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi
