apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami-oci
  namespace: flux-system
spec:
  interval: 1h
  type: oci # <--- This is the key fix!
  url: oci://registry-1.docker.io/bitnamicharts
