apiVersion: v1
kind: Namespace
metadata:
  name: apps-dev-01-frontend
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-dev-01-frontend
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps/dev-01/frontend/
  prune: true
  sourceRef:
    kind: GitRepository
    name: rendered-dev
  targetNamespace: apps-dev-01-frontend
  # Global variables for dev cluster
  postBuild:
    substitute:
      apps_env: "dev-01"
      apps_domain: "dev-01.mycluster.com"
