apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rabbitmq-cluster-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: rabbitmq-cluster-operator
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 4.x.x
  install:
    crds: CreateReplace
  interval: 1h
  upgrade:
    crds: CreateReplace
  values:
    fullnameOverride: rabbitmq-operator
