apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rabbitmq-cluster-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: rabbitmq-cluster-operator
      sourceRef:
        kind: HelmRepository
        name: bitnami-oci
        namespace: flux-system
      version: 4.4.34
  install:
    crds: CreateReplace
  interval: 1h
  upgrade:
    crds: CreateReplace
  values:
    clusterOperator:
      image:
        repository: bitnami/rabbitmq-cluster-operator
        tag: 4.4.34
    fullnameOverride: rabbitmq-operator
