apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: messaging
spec:
  interval: 5m

  chart:
    spec:
      chart: rabbitmq
      version: "12.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system

  install:
    createNamespace: true

  values:
    auth:
      username: admin
      password: admin
      erlangCookie: cookie123

    replicaCount: 3

    persistence:
      enabled: true
      size: 5Gi

    metrics:
      enabled: true

