apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/skiyl9x/portfolio.git
  ref:
    branch: dev      # <- Flux буде читати саме dev branch

