apiVersion: v1
kind: Namespace
metadata:
  name: rabbitmq
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: messaging
spec:
  chart:
    spec:
      chart: rabbitmq
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 12.x
  install:
    createNamespace: true
  interval: 5m
  values:
    auth:
      erlangCookie: cookie123
      password: admin
      username: admin
    metrics:
      enabled: true
    persistence:
      enabled: true
      size: 5Gi
    replicaCount: 3
