apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rabbitmq-cluster-operator
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: rabbitmq-cluster-operator
      version: "4.4.34"
      sourceRef:
        kind: HelmRepository
        name: bitnami-oci
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    
    clusterOperator:
      image:
        # We override the broken default tag with a known stable one
        tag: "4.4.34"
    fullnameOverride: "rabbitmq-operator"

