apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rabbitmq-cluster-operator
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: rabbitmq-cluster-operator
      version: "4.x.x" # Use the latest stable
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    fullnameOverride: "rabbitmq-operator"
